version: '3'
services:
 sqlserver:
  container_name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  environment: 
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "!Aa123456"
  ports: 
   - "1433:1433"
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  ports:
   - "15672:15672"
   - "5672:5672"
  environment:
   - RABBITMQ_DEFAULT_USER=guest
   - RABBITMQ_DEFAULT_PASS=guest      
 customermanagementapi:
  container_name: customermanagementapi
  image: mat/customermanagementapi
  build:
   context: .
   dockerfile: CustomerManagementAPI/Dockerfile
  depends_on:
   - rabbitmq
   - sqlserver
  ports:
    - "4000"
  environment:
   - ASPNETCORE_ENVIRONMENT=Production
 vehiclemanagementapi:
  container_name: vehiclemanagementapi
  image: mat/vehiclemanagementapi
  build:
   context: .
   dockerfile: VehicleManagementAPI/Dockerfile
  depends_on:
   - rabbitmq
   - sqlserver
  ports:
   - "4100"
  environment:
  - ASPNETCORE_ENVIRONMENT=Production
 workshopmanagementapi:
  container_name: workshopmanagementapi
  image: mat/workshopmanagementapi     
  build:
   context: .
   dockerfile: WorkshopManagementAPI/Dockerfile
  depends_on:
   - rabbitmq
   - sqlserver
  ports:
   - "4200" 
  environment: 
   - ASPNETCORE_ENVIRONMENT=Production     
 webapp:
  image: mat/webapp
  build:
   context: .
   dockerfile: WebApp/Dockerfile
  ports:
    - "5000:5000" 
  environment:
   - ASPNETCORE_ENVIRONMENT=Production    
 notificationservice:
  image: mat/notificationservice
  build:
   context: .
   dockerfile: NotificationService/Dockerfile
 workshopmanagementeventhandler:
  image: mat/workshopmanagementeventhandler
  build:
   context: .
   dockerfile: WorkshopManagementEventHandler/Dockerfile
